### PR TITLE
Use official php image

### PR DESCRIPTION
**Pull request by jbrinley**
A somewhat different direction...

1. Replaces phpdocker.io with the official PHP image from https://hub.docker.com/_/php
2. Merges @defunctl's entrypoint work from #1 
3. Replaces the custom user script with [fixuid](https://github.com/boxboat/fixuid)

Reasoning for using the official PHP image:
1. It's versioned more reliably that phpdocker, making our images more predictable
2. It's easier to install a wide variety of PHP core and PECL extensions using the built in scripts
3. It plays better with running as a non-root user

Drawbacks:
1. It results in a larger image size (~600MB instead of ~400MB)

Reasoning for using fixuid:
1. It handles permissions thoroughly and cleanly
2. It allows us to run the entire container as a non-root user, instead of just PHP-FPM

This creates a default user in the PHP container named `squareone`, UID of 1000. To run with a different UID, drop them in your `docker-compose.override.yml`.

```
services:
  php-fpm:
    user: 501:501
  php-tests:
    user: 501:501
```

Not only will PHP-FPM run as that user, any other commands you run in the container will also run as that user, including WP-CLI and composer.

### CODE REVIEW

**Comment by defunctl** [comment]
@jbrinley,

I'd like to further automate this vs a docker-compose.override.yml. I think the default square one docker-compose.yml should use environment variables with a sane default, e.g.

```
services:
  php-fpm:
    user: "${SQ1_UID:-1000}:${SQ1_GID:-1000}"
  php-tests:
    user: "${SQ1_UID:-1000}:${SQ1_GID:-1000}"
```

And they could be populated:

- Automatically  with `so` global docker.
- We could add `dev/docker/.env` to .gitignore if it's not already, and users could customize it there for those not using `so` global.

Thoughts?

**Comment by marcossantiago** [comment]
I really like the idea of managing our own Docker images. Could we potentially deprecate the old [docker-images ](github.com/moderntribe/docker-images) repo as well ? 

@defunctl We could automate even further using `.env`, specially replacing the [projectID](https://github.com/moderntribe/square-one/blob/epic/fidgety-feet/dev/docker/.projectID) and some other variables like [VIRTUAL_HOST](https://github.com/moderntribe/square-one/blob/741a82301a85f24d7b8a71c6b92313b4df3564d0/dev/docker/docker-compose.yml#L95). I have seen quite some wrong copy/pasta and a single .env would solve this issue.

**Comment by jbrinley** [comment]
> I'd like to further automate this vs a docker-compose.override.yml. I think the default square one docker-compose.yml should use environment variables with a sane default

Good call. When I make the corresponding SquareOne PR to use this image, I'll make that change.

> And they could be populated:
> * Automatically  with `so` global docker.
> * We could add `dev/docker/.env` to .gitignore if it's not already, and users could customize it there for those not using `so` global.

I like both ideas. Implementing both may be tricky, due to how [precedence works](https://docs.docker.com/compose/environment-variables/#the-env-file). E.g., I would expect values I put in my local `.env` file to take precedence, but because `so` would be setting them on the command line, it would override my values. Perhaps `so` only sets the values when it doesn't see an `.env` file in the project?

> Could we potentially deprecate the old docker-images repo as well ?

Yes, we can. I think I can remove them from Docker Hub, too. Very unlikely that anyone is using the images.

> We could automate even further using .env, specially replacing the projectID and some other variables like VIRTUAL_HOST.

An ignored `.env` file won't really help with that. We would need something that we commit to the repo.

**Comment by defunctl** [comment]
I really think we should solve this with `so`. This is only for Linux users, and they're always going to need this. On OSX/Windows it won't matter what the user is set to as the host will always be able to read/write to the container. As long as `docker-compose.yml` has environment variables we can modify at runtime we should be set.

I believe it should be a seamless, hidden experience. In my testing so far, [getmyuid()](https://www.php.net/manual/en/function.getmyuid.php) works accurately. 

Additionally it may be a better user experience to just provide the required commands with options/arguments to override the uid/gid environment variables for power users, e.g. `so start --uid=500 -gid=500` or something like that.

**Pull request merged**
